spring:
  application:
    name: ${SPRING_APPLICATION_NAME}

  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    show-sql: ${SPRING_JPA_SHOW_SQL}

  logging:
    level:
      root: ${LOGGING_LEVEL_ROOT}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: ${MAIL_PROPERTIES_MAIL_SMTP_AUTH}
      mail.smtp.starttls.enable: ${MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}
      mail.debug: ${MAIL_PROPERTIES_MAIL_DEBUG}
      mail.smtp.ssl.trust: ${MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST}

  servlet:
    multipart:
      enabled: ${SPRING_SERVLET_MULTIPART_ENABLED}
      max-request-size: ${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE}
      max-file-size: ${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE}

  security:
    oauth2:
      client:
        registration:
          kakao:
            authorization-grant-type: authorization_code
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            client-authentication-method: client_secret_post
            client-name: Kakao
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: ${NAVER_REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope: name
            client-name: Naver
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope:
              - email
              - profile
            client-name: Google
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

# IAMPORT
imp:
  code: ${IMP_CODE}
  api:
    key: ${IMP_API_KEY}
    secretkey: ${IMP_API_SECRET_KEY}

# AWS S3
cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    s3:
      bucket: ${CLOUD_AWS_S3_BUCKET}
    region:
      static: ${CLOUD_AWS_REGION_STATIC}
    stack:
      auto: ${CLOUD_AWS_STACK_AUTO}
